---
- hosts: all
  tasks:
    - include_vars: "locker_talk.yaml"

    - set_fact: deploy_password='{{ deploy_password }}'
    - set_fact: deploy_user='ansible'
    - set_fact: deploy_rsa_key='cluster_rsa'
    - set_fact: deployment_scope='os_deployer'
    - set_fact: deployment_group_id='999999'
    - set_fact: deployment_network='192.168.34.0/24'
    - set_fact: admin_user='vagrant'

- hosts: controller
  become: true
  gather_facts: false
  vars:
    admin_user: 'vagrant'

  tasks:
  - name: add the ansible user to the controller
    user:
      name: "{{ deploy_user }}"
      append: yes
      state: present
      generate_ssh_key: yes
      ssh_key_bits: 4048
      ssh_key_file: "/home/{{ deploy_user }}/.ssh/{{ deploy_rsa_key }}"
      ssh_key_type: rsa
  
  - name: Set the .ssh/config for the user
    template:
      src: ./templates/ssh_config.j2
      dest: "/home/{{ deploy_user }}/.ssh/config"
      owner: "{{ deploy_user }}"
      group: "{{ deploy_user }}"
      mode: 0440

  - name: copy the ansible generated public key for lookup resolution 
    copy:
      remote_src: true
      src: "/home/{{ deploy_user }}/.ssh/{{ deploy_rsa_key }}.pub"
      dest: "./tmp/{{ deploy_rsa_key }}.pub"
      mode: 0666
  
  - name: add admin user to ansible group
    user:
      name: "{{ admin_user }}"
      append: yes
      groups: "{{ deploy_user }}" 

  # - name: create the logical directory structure in the home directory
  # - name: create the /etc/ansible directory
  # - name: create the /home/ansible/defaults/ directory
  # - name: symbolic link the /etc/ansible references to /home/ansible/defaults/ directory
  # IS this a good idea?
  # so /etc/ansible/ansible.cfg ~ /home/ansible/defaults/_ansible.cfg
  # so /etc/ansible/hosts ~ /home/ansible/defaults/_hosts/
  # so /etc/ansible/... ~ /home/ansible/defaults/_...

  # - name: setup the ansible redis service for fact_checking


- hosts: compute:controller
  become: true
  gather_facts: false
  tasks:
  - name: add the group for the scoped deployers
    group:
      name: "{{ deployment_scope }}"
      gid: "{{ deployment_group_id }}"
      state: present
      system: yes

  - name: add the user
    user:
      name: "{{ deploy_user }}"
      password: "{{ deploy_password }}"
      append: yes
      comment: "kicking off greatness"
      groups: "{{ deployment_scope }}"
      state: present

  - name: add the sudoers policy for the deployers
    template:
      src: ./templates/sudoers_d.j2
      dest: /etc/sudoers.d/{{ deployment_scope }}
      owner: root
      group: root
      mode: 0440
      validate: 'visudo -cf %s'

- hosts: compute
  gather_facts: false
  become: true
  tasks:
  - name:
    authorized_key:
      user: "{{ deploy_user }}"
      state: present
      exclusive: yes
      manage_dir: yes
      key: "{{ lookup('file', './tmp/{{ deploy_rsa_key }}.pub') }}"
      path: "/home/{{ deploy_user }}/.ssh/authorized_keys"

